package com.proptech.partners.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PartnerDTO {
    public Long id;
    public String firstName;
    public String lastName;
    public String email;
    public String phone;
    public String documentNumber;
    public String documentType;
    public String type;
    public String status;
    public String companyName;
    public String companyRegistration;
    public String position;
    public String address;
    public String city;
    public String state;
    public String zipCode;
    public String country;
    public String website;
    public String socialMedia;
    public String bankAccount;
    public String bankName;
    public BigDecimal commissionRate;
    public LocalDateTime partnershipDate;
    public LocalDateTime contractStartDate;
    public LocalDateTime contractEndDate;
    public BigDecimal contractValue;
    public String currency;
    public String paymentFrequency;
    public LocalDateTime nextPaymentDate;
    public BigDecimal totalEarnings;
    public BigDecimal pendingEarnings;
    public LocalDateTime lastPaymentDate;
    public BigDecimal lastPaymentAmount;
    public Long assignedAgentId;
    public Long assignedAgencyId;
    public String notes;
    public String specializations;
    public String territories;
    public String languages;
    public String certifications;
    public Integer experienceYears;
    public Integer propertiesManaged;
    public Integer successfulDeals;
    public BigDecimal averageRating;
    public Integer totalReviews;
    public Boolean isVerified;
    public LocalDateTime verificationDate;
    public LocalDateTime createdAt;
    public LocalDateTime updatedAt;
    public String photo;
} 